### ISSUE TITLE
Unify Limenius and answear fork

### ISSUE THREAD

**Issue by tacman** [Limenius/Liform#72]
I've submitted some PRs to answear's fork of this library: https://github.com/answear/Liform/pulls

I also have my own fork of answear's liform-bundle, which of course needs liform, but didn't work with the latest Symfony dependency injection.  I don't care which version of Liform the bundle uses, as long as it's current and works with my bundle without bombarding me with deprecation messages.

My request is that this repo and https://github.com/answear/Liform unify so that developers don't need to choose which library to use.

Perhaps a new release that drops unsupported dependencies?  PHP 7 is dead, Symfony < 5.4 is dead (and 5.4 will be EOL very shortly).  

I'm happy to contribute PRs to support that, but I'm not sure to which repo I should be submitting them.  

This is a really cool library, I struggled to find PHP code to generate a schema that followed existing standards.  Creating the schema from a form is a clever idea, and this implementation looks like it will work very well for my application, so thanks again for releasing it.

**Comment by EmaGit1** [comment]
Hello @tacman, this library is cool for me too and I'm using it in my personal project.
But working with PHP 8 and Symfony 6.4 I couldn't use it so I tried the [(https://github.com/answear/Liform](https://github.com/answear/Liform) and everything works fine except for deprecation messagges.

I'm writing to ask you if it is possibile to unify your fork with the answear's, because he added some features that I need (for example the managing of symfony form "priority" key to sort the elements in the result schema) and fixed some bugs.
Or at least carry over its changes in your fork.

I would like not to have to create another fork from this repository with your changes and those of answear.
I wish I could use your fork directly, thus eliminating all the annoying deprecation messages.

Thank you in advance

**Comment by tacman** [comment]
Sure, I'm happy to, if I can figure out how!  Literally, I'm not that good with merging branches.

Better, of course, would be for this branch, the original, to merge answer's fork and my fork, creating a new release if necessary that only supports maintained versions of the libraries.

can you point me to the step on how to merge answer's fork?  My fork is even more restrictive, as it requires at least Symfony 6.4 and PHP 8.1

**Comment by tacman** [comment]
I think I figured out the merge.  How important is Symfony 5.4 to you?

**Comment by tacman** [comment]
I merged answear, and tests pass.  Can you review it, and if so, I'll merge it with my branch and publish a new release.

https://github.com/survos/Liform/tree/with-answear

**Comment by EmaGit1** [comment]
Symfony 5.4 is not important to me, I would like to migrate to Symfony 7 in the future...

I reviewed the merged files and everything comes back to me. I also did some quick tests and everything seems to be working fine and finally the deprecation messages are gone.

I really don't know how to thank you for your quick response and edits.

I'm waiting for your new release.

**Comment by tacman** [comment]
Done, 1.1 is released!  Enjoy.

I can submit a PR here if it'll be accepted, but at this point perhaps it's diverged too much.

**Comment by tacman** [comment]
I _think_ this repo now is current.
